## Question-1 :What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

In [1]:
## Ordinal encoding should be used for ordinal variables (where order matters, like cold , warm , hot ); vs Label encoding should be used for non-ordinal (aka nominal) variables (where order doesn't matter, like blonde , brunette )

## Question-2 :Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

In [3]:
## Target-guided ordinal encoding involves replacing the categories in the categorical variable with ordinal numbers that are based on the relationship between the category and the target variable.

In [4]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [5]:
df.head()

city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [6]:
df_mean=df.groupby('city')['price'].mean()

In [12]:
mean=df_mean.to_dict()

In [14]:
df['city_encoded']=df['city'].map(mean)

In [18]:
df

city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

## Question-3 :Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [19]:
## Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we can say, in other words, it defines the changes between the two variables, such that change in one variable is equal to change in another variable.

## Question-5 :Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [20]:
## The variance-covariance matrix is a square matrix with diagonal elements that represent the variance and the non-diagonal components that express covariance. The covariance of a variable can take any real value- positive, negative, or zero. A positive covariance suggests that the two variables have a positive relationship, whereas a negative covariance indicates that they do not. If two elements do not vary together, they have a zero covariance.

In [ ]:
3 ⨯ 3 Covariance Matrix
In a 3⨯3 Matrix there are 3 rows and 3 columns. We know that in a Covariance Matrix the diagonal elements are variance and non-diagonal elements are covariance. Hence, a 3⨯3 Covariance Matrix can be given as \begin{bmatrix}\mathrm{var(x)}&\mathrm{cov(x,y)} &\mathrm{cov(x,z)} \\\mathrm{cov(x,y)} &\mathrm{var(y)} &\mathrm{cov(y,z)} \\\mathrm{cov(x,z)} &\mathrm{cov(y,z)} &\mathrm{var(z)} \\\end{bmatrix}     

In [32]:
import numpy as np
Age=[23,24,25,26,37]
income=[12000,1300,23000,24000,26000]
education_level=[12,10,11,9,8]
data=np.array([[23,24,25,26,37],[1200,1300,23000,24000,26000],[12,10,11,9,8]])
print(np.cov(data))

[[ 3.2500e+01  4.5325e+04 -7.2500e+00]
 [ 4.5325e+04  1.6102e+08 -1.2650e+04]
 [-7.2500e+00 -1.2650e+04  2.5000e+00]]


## Question-4 :For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [46]:
df=pd.DataFrame({'color':['red','green','blue'],'size':['small','medium','large'],'material':['wood','metal','plastic']})

In [47]:
from sklearn.preprocessing import LabelEncoder

In [51]:
encoder=LabelEncoder()
encoder.fit_transform(df['color'])

array([2, 1, 0])

In [52]:
encoder.fit_transform(df['size'])

array([2, 1, 0])

## Question-6 :You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

In [53]:
df=pd.DataFrame({"Gender":["Male","female"],"Education+Level":["school","Bachelor's"],"Employment_status":["unemployed","part-time"]})

In [54]:
df

Gender Education+Level Employment_status
0    Male          school        unemployed
1  female      Bachelor's         part-time

In [55]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [56]:
encoder.fit_transform(df["Gender"])

array([0, 1])

In [58]:
encoder.fit_transform(df["Education+Level"])

array([1, 0])

## Question-7 You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.